name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_USERNAME: the-mesh-for-data
  GO_VERSION: 1.13

jobs:
  build:
    name: Build and push img
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-ut-m2-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-ut-m2
    - name: Build
      run: make build
    - name: Docker login
      if: ${{ github.event_name != 'pull_request' }}
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin "${{ env.DOCKER_HOSTNAME }}"
    - name: Docker build
      run: docker build . -t ghcr.io/the-mesh-for-data/vault-plugin-secrets-kubernetes-reader:latest -f Dockerfile
    - name: Docker push
      if: ${{ github.event_name != 'pull_request' }}
      run: docker push ghcr.io/the-mesh-for-data/vault-plugin-secrets-kubernetes-reader:latest

