name: Build

on:
  push:
    branches:
      - master
      - gh_actions
  pull_request:
    branches:
      - master

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_USERNAME: the-mesh-for-data
  ACTIVE_CI: gh_actions #  This parameter defines which CI should push to the docker repository

jobs:
  test:
    name: Img push
    runs-on: ubuntu-latest
    - name: Docker login
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      run: docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin "${{ env.DOCKER_HOSTNAME }}"
    - name: Docker build
      run: docker build . -t ghcr.io/the-mesh-for-data/vault-plugin-secrets-kubernetes-reader:latest -f Dockerfile
    - name: Docker push
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      run: docker push ghcr.io/the-mesh-for-data/vault-plugin-secrets-kubernetes-reader:latest

