name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1
        with:
          args: --timeout 5m
          version: v1.29
          skip-go-installation: true
      - name: Run vet
        run: go vet ./...
